### ISSUE TITLE
Bug: subtile timestamps are reversed.

### ISSUE THREAD

**Issue by mataka123** [bindestriche/srt_fix#11]
Subs fixed with srt_fix_stdlib.exe have subtile timestamps are reversed. I.e.:
1
00:00:06,769 --> 00:00:04,610
how is the day treating you so far so

2
00:00:07,909 --> 00:00:06,779
good yeah go to the gym a little bit

**Comment by bindestriche** [comment]
Can you provide a YouTube example link ?

mataka123 ***@***.***> schrieb am Sa., 13. Jan. 2024, 19:23:

**Comment by mataka123** [comment]
I tried with multiple links and same result. This is last link i used: https://www.youtube.com/watch?v=i7Xir9ogmhY

**Comment by bindestriche** [comment]
new commit should fix the problem. thank you for your report
