### ISSUE TITLE
[srt_fix] post-processed 'xxx.mp4' with {}

### ISSUE THREAD

**Issue by ghost** [bindestriche/srt_fix#5]
![image](https://github.com/bindestriche/srt_fix/assets/52028866/af8ad7ff-74fe-4f20-8d0b-93ecdf64241e)

Hi, I'm using the latest version of yt-dlp, and my options are (through .conf file):
`-P "%DOWNLOADS%" -o "%(title)s.%(ext)s" -S ext --write-auto-sub --sub-lang en --convert-subs=srt --use-postprocessor srt_fix`
But no fixed.srt file generated after run.
Could you help find the problem? Thanks.

**Comment by bindestriche** [comment]
> Does the project even work?
It works for me, I would ask you to consider that I am not an experience developer.
If you could please provide me with a link to a video that causes the issues, that would be great.

Also please redownload the latest merge does include a fix for the -o option, maybe that is all you need.

the gui py indeed had a silly error, that should also be fixed now
