### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by GitEin11** [bindestriche/srt_fix#6]
I get this error
when trying to run the python

Traceback (most recent call last):
  File "./srt_fixer_gui.py", line 49, in <module>
    class SimpleSrt:
  File "./srt_fixer_gui.py", line 80, in SimpleSrt
    def get_duration(parts: list[int, int, int, int]) -> timedelta:
TypeError: 'type' object is not subscriptable

**Comment by GitEin11** [comment]
nvm I manage to run the .exe thru wine

**Comment by bindestriche** [comment]
great that you got it to work for you, but the issue is still there. It's mad to run a python program through wine, it should work directly. I'd love to fix it. What is "the python" ? on what os are you ? what python version do you have?

**Comment by GitEin11** [comment]
I run
>python3 srt_fixer_gui.py

then I get that error

using:
Python 3.8.10
Ubuntu 20.04.6 LTS x86_64

**Comment by bindestriche** [comment]
@GitEin11 thank you the issue was that typehints are not supported by your version, I removed them, it should work now
