### ISSUE TITLE
AttributeError: module 'os' has no attribute 'oath'. Did you mean: 'path'?

### ISSUE THREAD

**Issue by profucius** [bindestriche/srt_fix#7]
I've downloaded and ran the `srt_fixer_cli.py` on a subtitle file. I then get the error `AttributeError: module 'os' has no attribute 'oath'. Did you mean: 'path'?` referencing lines 72 and 74. I believe this may be a typo, the `oath` should be `path`. Once I changed both those oath to path, saved the file and ran the script again, it successfully converts the subtitle with no errors.

![image](https://github.com/bindestriche/srt_fix/assets/18254607/9f4812d2-11cd-42db-925f-bff2e5dd138a)

**Comment by bindestriche** [comment]
Thanks you foe talking the time to write all thia Reports. Indeed it should
be Join path. Ods how I missed this.

Andrew ***@***.***> schrieb am Sa., 16. Dez. 2023, 17:32:
