### ISSUE TITLE
Installation instructions for `srt_fixer_cli.py`

### ISSUE THREAD

**Issue by profucius** [bindestriche/srt_fix#8]
Your documentation is helpful and got me running on the `srt_fix.py` as well as the `GUI`. However the documentation regarding how and where to install `srt_fixer_cli.py` is a bit sparse. It assumes the user knows where to place the files and how to do so. There is no python install command for installing it, so I made the assumption that I should manually download the repo, and drop all the files within the already downloaded `postprocessor` (from the srt_fix install process). 

This does work, however in the event I need to reinstall windows, I will need to remember to manually do this process again. It would be helpful if you added some lines to the Readme about how to install `srt_fixer_cli.py` via pip or such. Thank you

**Comment by bindestriche** [comment]
Thats a good point. I don't know enough about pip. I figured people using a command line tool will also be fine with coping two files .To use the tool you need to have simplesrt.py and srt_fixer_cli.py in the same directory. I did mention that in the readme .
