### ISSUE TITLE
Download subtitles without video

### ISSUE THREAD

**Issue by profucius** [bindestriche/srt_fix#9]
You're probably already aware, but I noticed you created a ticket [here](https://github.com/yt-dlp/yt-dlp/issues/6986) regarding skipping the video download while allowing postprocessing to continue. I just wanted to bring to your attention that you got a reply on that thread months after your original post. I tested it out in my environment, and it does in fact work. There may be some tweaking necessary in the srt_fix invocation afterwards, but overall I think this would be a great addition to your script. At least as a fork for those who want to only download subtitles.

**Comment by bindestriche** [comment]
Thank you very much for making me aware of it. I did now implement a fix according to that template
